# wip

env:
  global:
    - GOAL=FURYF4OSD
    - PATH=$HOME/.local/bin:$PATH

sudo: false

git:
  depth: 10

addons:
  apt:
    packages:
      - build-essential
      - git
      - lcov
      - libblocksruntime-dev
      - libc6-i386
      - time

language: cpp
compiler: clang
dist: bionic

before_install:
  - pip install --user --upgrade cpp-coveralls
  - gem install coveralls-lcov

install:
  - make arm_sdk_install

before_script:
  - tools/gcc-arm-none-eabi-7-2017-q4-major/bin/arm-none-eabi-gcc --version
  - clang --version
  - clang++ --version
  - gcc --version

script: 
  - ./.travis.sh

deploy:
  provider: bintray
  file: "bintray-conf.json"
  user: "$BINTRAY_USER"
  key: "$BINTRAY_API_KEY"
  skip_cleanup: true

cache:
  directories:
  - downloads
  - tools

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
