os:
  - linux
  - osx
  - windows

sudo: false

dist: bionic
language: node_js

addons:
  apt:
    packages:
      - rpm
  chrome: stable

git:
  depth: 5 # quick clone
  quiet: true # save on logfiles

node_js:
  - 10

before_install:
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then choco install python; fi
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then export PATH="/c/Python37:/c/Python37/Scripts:$PATH"; fi
  #- if [ "$TRAVIS_OS_NAME" == "osx" ]; then export PATH="$HOME/.local/bin:$PATH"; fi

install:
  - pip install --upgrade j2cli

script: 
  - ./.travis.sh # main

cache:
  yarn: true
  directories:
  - node_modules
  - cache

deploy:
  provider: bintray
  file: bintray-conf.json
  user: "$BINTRAY_USER"
  key: "$BINTRAY_API_KEY"
  skip_cleanup: true # do not delete what has just been built
  edge: true # "dpl" v2
  on:
    #all_branches: true
    branch: ci_presets # just this specific branch

after_deploy:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
