# wip

env:
  - GOAL=FURYF4OSD

sudo: false

git:
  depth: 10

addons:
  apt:
    packages:
      - build-essential
      - git
      - lcov
      - libblocksruntime-dev
      - libc6-i386
      - time
  artifacts:
    s3_region: "us-west-2"
    paths:
      - $(ls obj/*.hex | tr "\n" ":")
      #- $(ls obj/*.bin | tr "\n" ":")
    target_paths:
      - /$TRAVIS_BUILD_NUMBER/emuflight/
    #debug: true 

language: cpp
compiler: clang
dist: bionic

before_install:
  - pip install --user cpp-coveralls
  - gem install coveralls-lcov

install:
  - make arm_sdk_install

before_script:
  - tools/gcc-arm-none-eabi-7-2017-q4-major/bin/arm-none-eabi-gcc --version
  - clang --version
  - clang++ --version
  - gcc --version

script: ./.travis.sh

cache:
  directories:
  - downloads
  - tools

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
