# wip

env:
  - GOAL=FURYF4OSD

sudo: false

git:
  depth: 10

addons:
  apt:
    packages:
      - lcov
      - build-essential
      - git
      - libc6-i386
      - time
      - libblocksruntime-dev
  # artifacts:
  #   s3_region: "us-west-2"
  #   paths:
  #     - $(ls obj/*.hex | tr "\n" ":")
  #     - $(ls obj/*.bin | tr "\n" ":")
  #   target_paths:
  #     - /$TRAVIS_BUILD_NUMBER/Emuflight/

language: cpp
compiler: clang
dist: bionic

before_install:
  - pip install --user cpp-coveralls
  - gem install coveralls-lcov

install:
  - make arm_sdk_install

before_script:
  - tools/gcc-arm-none-eabi-7-2017-q4-major/bin/arm-none-eabi-gcc --version
  - clang --version
  - clang++ --version
  - gcc --version

script: ./.travis.sh

cache:
  directories:
  - downloads
  - tools
