env:
  - RUNTESTS=True
  - TARGET=CC3D
  - TARGET=CC3D OPBL=yes
  - TARGET=CHEBUZZF3
  - TARGET=CJMCU
  - TARGET=EUSTM32F103RC
  - TARGET=SPRACINGF3
  - TARGET=NAZE
  - TARGET=NAZE32PRO
  - TARGET=OLIMEXINO
  - TARGET=PORT103R
  - TARGET=SPARKY
  - TARGET=STM32F3DISCOVERY
  - TARGET=ALIENWIIF1
  - TARGET=ALIENWIIF3
# We use cpp for unit tests, and c for the main project.
language: cpp
compiler: clang

before_install: 
  - sudo apt-get update
  # The PPA doesn't have a package for Trusty for 4.8, so manually download the Saucy build
  - wget "http://ppa.launchpad.net/terry.guo/gcc-arm-embedded/ubuntu/pool/main/g/gcc-arm-none-eabi/gcc-arm-none-eabi_4-8-2014q2-0saucy9_amd64.deb"

install: 
   - sudo apt-get install build-essential git
   - sudo dpkg -i gcc-arm-none-eabi_4-8-2014q2-0saucy9_amd64.deb
   
before_script: arm-none-eabi-gcc --version
script: ./.travis.sh

notifications:
  irc: "chat.freenode.net#cleanflight"
  use_notice: true
  skip_join: true
