os:
  - linux
  - osx
  - windows

sudo: false

osx_image: xcode11.2
dist: bionic # linux
language: node_js

addons:
  chrome: stable

git:
  depth: 5 # quick clone
  quiet: true # save on logfiles

node_js:
  - 10 # version

before_install:
  # install nsis on windows
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then choco install nsis; fi
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then export PATH="/c/Program Files (x86)/NSIS:$PATH"; fi
  # install python on all platforms supported
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then choco install python --version 3.8.0; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export PATH="$HOME/.local/bin:$PATH"; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export PATH="$HOME/Library/Python/2.7/bin:$PATH"; fi

install:
  - python -m pip install --user --upgrade j2cli # install pip

script:
  - ./.travis.sh # main

cache:
  pip: true
  yarn: true
  directories:
  - cache
  - '/c/Users/travis/AppData/Local/Temp/chocolatey'

deploy:
  provider: bintray
  file: bintray-conf.json
  user: "$BINTRAY_USER"
  key: "$BINTRAY_API_KEY"
  skip_cleanup: true # do not delete what has just been built
  edge: true # dpl v2
  on:
    #all_branches: true
    branch: ci_presets # just this specific branch

after_deploy:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
