# wip

env:
  global:
    - TARGET=FURYF4OSD # make $TARGET
    - PATH=$HOME/.local/bin:$PATH # "user" installs

sudo: false

git:
  depth: 5 # quick clone
  quiet: true

addons:
  apt:
    packages:
      - build-essential
      - git
      #- lcov
      - libblocksruntime-dev # TODO: required?
      - libc6-i386
      - time

cache:
  directories:
  - downloads
  - tools

dist: bionic # ubuntu
language: cpp
compiler: clang

before_install:
  - pip install --user --upgrade j2cli
install:
  - make arm_sdk_install # toolchain

before_script:
  - tools/gcc-arm-none-eabi-7-2017-q4-major/bin/arm-none-eabi-gcc --version # TODO: this recent? check Makefile
  - clang --version
  - clang++ --version
  - gcc --version

script: 
  - ./.travis.sh # main

deploy:
  provider: bintray
  file: bintray-conf.json
  user: "$BINTRAY_USER"
  key: "$BINTRAY_API_KEY"
  skip_cleanup: true
  edge: true # dpl v2
  on:
    branch: continous_disintegration # name of this branch

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
