# wip

env:
  global:
    - GOAL=FURYF4OSD # make $GOAL
    - PATH=$HOME/.local/bin:$PATH # "user" installs

sudo: false

git:
  depth: 10 # quick clone

addons:
  apt:
    packages:
      - build-essential
      - git
      - jq
      - lcov
      - libblocksruntime-dev # required?
      - libc6-i386
      - time

cache:
  directories:
  - downloads
  - tools

dist: bionic # ubuntu
language: cpp
compiler: clang

before_install:
  - pip install --user --upgrade cpp-coveralls # not used for now
  - gem install coveralls-lcov # not used for now

install:
  - make arm_sdk_install # toolchain

before_script:
  - tools/gcc-arm-none-eabi-7-2017-q4-major/bin/arm-none-eabi-gcc --version # TODO: this recent? check Makefile
  - clang --version
  - clang++ --version
  - gcc --version

script: 
  - ./.travis.sh # main

before_deploy:
  - jq --arg version "0.99" --arg branch xybranch \
'.version.name = $version, .package.name = $branch' bintray-conf.json


deploy:
  provider: bintray
  file: "bintray-conf.json"
  user: "$BINTRAY_USER"
  key: "$BINTRAY_API_KEY"
  skip_cleanup: true
  edge: true # dpl v2
  on:
    branch: continous_disintegration # TODO: scope

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
